import{a as b,i as a,S as R}from"./assets/vendor-F1LeQrrD.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function e(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(t){if(t.ep)return;t.ep=!0;const o=e(t);fetch(t.href,o)}})();async function g(s,r=1){if(s)try{return(await b.get("https://pixabay.com/api/",{params:{key:"14797936-c0ac273b2bc1360021fe4ee91",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15}})).data}catch(e){a.show({color:"red",position:"topRight",message:e.message})}}let S=new R(".gallery a",{captionsData:"alt",captionDelay:250,captionPosition:"outside"});const p=document.querySelector(".gallery"),m=document.querySelector(".loader"),y=document.querySelector(".loadmore");function h(s){const r=s.map(e=>`<li class="gallery-item">
        <a class="gallery-link" href="${e.largeImageURL}">
        <img class="gallery-img" src="${e.webformatURL}" alt="${e.tags}" width="360">
        </a>
        <div class="gallery-stats">
        <div class="gallery-count-wrap"><p class="gallery-counter">Likes</p>
        <p class="gallery-count">${e.likes}</p></div>
        <div class="gallery-count-wrap"><p class="gallery-counter">Views</p>
        <p class="gallery-count">${e.views}</p></div>
        <div class="gallery-count-wrap"><p class="gallery-counter">Comments</p>
        <p class="gallery-count">${e.comments}</p></div>
        <div class="gallery-count-wrap"><p class="gallery-counter">Downloads</p>
        <p class="gallery-count">${e.downloads}</p></div>
        </div>
        </li>`).join("");p.insertAdjacentHTML("beforeend",r),S.refresh()}function q(){p.innerHTML=""}function f(){m.classList.remove("hidden")}function w(){m.classList.add("hidden")}function v(){y.classList.remove("hidden")}function d(){y.classList.add("hidden")}const $=document.querySelector(".form"),P=document.querySelector(".loadmore");let l=1,u="",n=0,L=0;$.addEventListener("submit",async s=>{s.preventDefault();const r=s.target.elements["search-text"];if(r.value===""){a.show({color:"red",position:"topRight",message:"Please type in something"});return}l=1,n=0,u=r,q(),f(),d();try{const e=await g(u,l);if(e.hits.length===0){a.show({color:"red",position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"});return}n=e.totalHits,h(e.hits);const i=document.querySelector(".gallery-item");L=i?i.getBoundingClientRect().height:0,n>15?v():a.show({color:"red",position:"topRight",message:"We're sorry, but you've reached the end of search results."})}catch(e){a.show({color:"red",position:"topRight",message:e.message})}finally{w()}});P.addEventListener("click",async s=>{if(u){l++,f(),d();try{const r=await g(input.value,l);h(r.hits),window.scrollBy({top:L*2,behavior:"smooth"}),l>=Math.ceil(n/15)?(d(),a.show({color:"red",position:"topRight",message:"We're sorry, but you've reached the end of search results."})):v()}catch(r){a.show({color:"red",position:"topRight",message:r.message})}finally{w()}}});
//# sourceMappingURL=index.js.map
