import{a as L,S as b,i as n}from"./assets/vendor-I-4NK6U0.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&c(i)}).observe(document,{childList:!0,subtree:!0});function o(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(t){if(t.ep)return;t.ep=!0;const r=o(t);fetch(t.href,r)}})();async function u(s,e=1){if(s)try{return(await L.get("https://pixabay.com/api/",{params:{key:"14797936-c0ac273b2bc1360021fe4ee91",q:s,image_type:"photo",orientation:"horizontal",safesearch:!1,page:e,per_page:15}})).data}catch(o){iziToast.show({color:"red",position:"topRight",message:o.message})}}let S=new b(".gallery a",{captionsData:"alt",captionDelay:250,captionPosition:"outside"});const g=document.querySelector(".gallery"),p=document.querySelector(".loader"),m=document.querySelector(".loadmore");function y(s){const e=s.map(o=>`<li class="gallery-item">
        <a class="gallery-link" href="${o.largeImageURL}">
        <img class="gallery-img" src="${o.webformatURL}" alt="${o.tags}" width="360">
        </a>
        <div class="gallery-stats">
        <div class="gallery-count-wrap"><p class="gallery-counter">Likes</p>
        <p class="gallery-count">${o.likes}</p></div>
        <div class="gallery-count-wrap"><p class="gallery-counter">Views</p>
        <p class="gallery-count">${o.views}</p></div>
        <div class="gallery-count-wrap"><p class="gallery-counter">Comments</p>
        <p class="gallery-count">${o.comments}</p></div>
        <div class="gallery-count-wrap"><p class="gallery-counter">Downloads</p>
        <p class="gallery-count">${o.downloads}</p></div>
        </div>
        </li>`).join("");g.insertAdjacentHTML("beforeend",e),S.refresh()}function $(){g.innerHTML=""}function f(){p.classList.remove("hidden")}function h(){p.classList.add("hidden")}function q(){m.classList.remove("hidden")}function v(){m.classList.add("hidden")}const P=document.querySelector(".form");let a=1;const R=document.querySelector(".loadmore");let l,d,w;P.addEventListener("submit",s=>{if(s.preventDefault(),l=s.target.elements["search-text"],l.value===""){n.show({color:"red",position:"topRight",message:"Please type in something"});return}a=1,$(),f(),v(),u(l.value,a).then(e=>{e.length===0?n.show({color:"red",position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"}):(d=e.totalHits,y(e.hits),w=document.querySelector(".gallery-item").getBoundingClientRect().height)}).finally(e=>{h(),a>d/15||q()})});R.addEventListener("click",s=>{a++,f(),u(l.value,a).then(e=>{a>e.totalHits/15&&(v(),n.show({color:"red",position:"topRight",message:"We're sorry, but you've reached the end of search results."})),y(e.hits),window.scrollBy({top:w*2,left:0,behavior:"smooth"})}).finally(()=>{h()})});
//# sourceMappingURL=index.js.map
